class SettingsEnvBOMissing(Exception): pass
class SettingsInImisMissing(Exception): pass
class SettingsBONotFound(Exception): pass
class SettingsPropertyNotFound(Exception): pass
class SettingsPropertyInBONotFound(Exception): pass
class SettingsBOWrongType(Exception): pass
class SettingsMissingOrEmptyMemberTypes(Exception): pass
class SettingsLapseMissingOrEmptyStartDate(Exception): pass
class SettingsLapseMissingOrEmptyEndDate(Exception): pass
class SettingsSingleLapseMissingOrEmptyIMISID(Exception): pass
class SettingsSingleLapseMissingOrEmptyDateToSkip(Exception): pass